function fig = graficos()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load graficos

h0 = figure('Color',[0 0 0], ...
	'Colormap',mat0, ...
	'FileName','C:\MATLABR11\work\graficos.m', ...
	'Name','Conjuntos', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[325 272 560 420], ...
	'Tag','Fig2', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0], ...
	'FontSize',13, ...
	'ForegroundColor',[1 0 0], ...
	'ListboxTop',0, ...
	'Position',[21 237.75 69.75 38.25], ...
	'String','Posição Inicial', ...
	'Style','text', ...
	'Tag','texto1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0], ...
	'FontSize',12, ...
	'ForegroundColor',[1 0 0], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[15 212.25 78.75 19.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','posicao');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0], ...
	'Callback','plotargraf', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[159.75 179.25 97.5 27], ...
	'String','Plotar', ...
	'Tag','botao');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0], ...
	'FontSize',13, ...
	'ForegroundColor',[1 0 0], ...
	'ListboxTop',0, ...
	'Position',[118.5 240.75 73.5 33.75], ...
	'String','Velocidade Inicial', ...
	'Style','text', ...
	'Tag','texto2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0], ...
	'FontSize',13, ...
	'ForegroundColor',[1 0 0], ...
	'ListboxTop',0, ...
	'Position',[222 252.75 73.5 21], ...
	'String','Aceleração', ...
	'Style','text', ...
	'Tag','texto3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0], ...
	'FontSize',13, ...
	'ForegroundColor',[1 0 0], ...
	'ListboxTop',0, ...
	'Position',[332.25 237 66.75 36], ...
	'String','Tempo Final', ...
	'Style','text', ...
	'Tag','texto4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0], ...
	'FontSize',12, ...
	'ForegroundColor',[1 0 0], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[116.25 213 78.75 19.5], ...
	'String','-3', ...
	'Style','edit', ...
	'Tag','velocidade');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0], ...
	'FontSize',12, ...
	'ForegroundColor',[1 0 0], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[221.25 213 78.75 19.5], ...
	'String','1.5', ...
	'Style','edit', ...
	'Tag','aceleracao');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0], ...
	'FontSize',12, ...
	'ForegroundColor',[1 0 0], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[325.5 213 78.75 19.5], ...
	'String','5', ...
	'Style','edit', ...
	'Tag','tempo');
if nargout > 0, fig = h0; end
