function fig2 = sobre()

load sobre

	h2 = figure('Color',[0 0 0], ...
		'Colormap',mat0, ...
		'FileName','C:\MATLABR11\work\sobre.m', ...
		'PaperPosition',[18 180 576 432], ...
		'PaperUnits','points', ...
		'Position',[325 272 170 85], ...
		'Tag','Fig2', ...
   	'ToolBar','none', ...
   	'Name','Sobre', ...
      'Resize','off');
   h3 = uicontrol('Parent',h2, ...
		'Units','points', ...
      'BackgroundColor',[0 0 0], ...
      'ForegroundColor',[1 0 0], ...
		'FontSize',13, ...
		'ListboxTop',0, ...
		'Position',[10 35 100 18.75], ...
		'String','Créditos para:', ...
		'Style','text', ...
      'Tag','texto');
    h3 = uicontrol('Parent',h2, ...
		'Units','points', ...
      'BackgroundColor',[0 0 0], ...
      'ForegroundColor',[1 1 1], ...
		'FontSize',10, ...
		'ListboxTop',0, ...
		'Position',[15 15 100 13], ...
		'String','Douglas, Eduardo,', ...
		'Style','text', ...
      'Tag','texto');
   h3 = uicontrol('Parent',h2, ...
		'Units','points', ...
      'BackgroundColor',[0 0 0], ...
      'ForegroundColor',[1 1 1], ...
		'FontSize',10, ...
		'ListboxTop',0, ...
		'Position',[15 3 100 13], ...
		'String','Gabriel, Pedro', ...
		'Style','text', ...
		'Tag','texto');
if nargout > 0, fig2 = h2; end
